using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace NativeForms.Generators;

/// <summary>
/// Turns <c>[Bindable]</c> into a compile-time member lookup, so a list control can resolve a
/// <c>DisplayMember</c> name without reflection (PRD §6).
/// </summary>
/// <remarks>
/// The emitted member is a <see langword="switch"/> from name to a static lambda reading that property.
/// The switch is what makes this worth generating: the C# compiler turns a string switch of any size into
/// a hash jump, so the lookup is constant-time, and every accessor is a direct property read the AOT
/// compiler can see — where <c>PropertyInfo.GetValue</c> is neither.
/// </remarks>
[Generator]
public sealed class BindableMemberGenerator : IIncrementalGenerator {
  private const string MarkerAttribute = "Hawkynt.NativeForms.BindableAttribute";

  /// <summary>
  /// The generated member is a partial implementation, so the class has to be one — and cannot be
  /// nested, since the generated file reopens it by namespace and name alone.
  /// </summary>
  private static readonly DiagnosticDescriptor _MustBePartial = new(
      "NFG004",
      "[Bindable] requires a non-nested partial class",
      "'{0}' is marked [Bindable] but is not a non-nested partial class, so no member lookup was generated",
      "NativeForms",
      DiagnosticSeverity.Error,
      isEnabledByDefault: true);

  /// <inheritdoc/>
  public void Initialize(IncrementalGeneratorInitializationContext context) {
    var models = context.SyntaxProvider.ForAttributeWithMetadataName(
        MarkerAttribute,
        predicate: static (node, _) => node is ClassDeclarationSyntax,
        transform: static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol);

    context.RegisterSourceOutput(models, static (spc, symbol) => Emit(spc, symbol));
  }

  private static void Emit(SourceProductionContext spc, INamedTypeSymbol type) {
    var declaredPartial = false;
    foreach (var reference in type.DeclaringSyntaxReferences)
      if (reference.GetSyntax() is ClassDeclarationSyntax c && c.Modifiers.ToString().Contains("partial"))
        declaredPartial = true;

    if (type.ContainingType is not null || !declaredPartial) {
      spc.ReportDiagnostic(Diagnostic.Create(
          _MustBePartial, type.Locations.Length > 0 ? type.Locations[0] : Location.None, type.Name));
      return;
    }

    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated/>");
    sb.AppendLine("#nullable enable");

    var hasNamespace = !type.ContainingNamespace.IsGlobalNamespace;
    if (hasNamespace) {
      sb.Append("namespace ").Append(type.ContainingNamespace.ToDisplayString()).AppendLine();
      sb.AppendLine("{");
    }

    var self = type.ToDisplayString();
    sb.Append("    partial class ").Append(type.Name)
      .AppendLine(" : global::Hawkynt.NativeForms.IBindableMembers");
    sb.AppendLine("    {");
    sb.AppendLine("        /// <summary>The accessor for a public readable property of this type, or null.</summary>");
    sb.AppendLine("        public static global::System.Func<object?, object?>? GetMemberAccessor(string memberName)");
    sb.AppendLine("            => memberName switch");
    sb.AppendLine("            {");

    foreach (var member in type.GetMembers()) {
      if (member is not IPropertySymbol prop
          || prop.DeclaredAccessibility != Accessibility.Public
          || prop.GetMethod is null
          || prop.IsStatic
          || prop.IsIndexer)
        continue;

      sb.Append("                \"").Append(prop.Name).Append("\" => static o => ((")
        .Append(self).Append(")o!).").Append(prop.Name).AppendLine(",");
    }

    sb.AppendLine("                _ => null,");
    sb.AppendLine("            };");
    sb.AppendLine("    }");

    if (hasNamespace)
      sb.AppendLine("}");

    spc.AddSource($"{type.Name}.Bindable.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
  }
}
