using System.Collections.Generic;
using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace NativeForms.Generators;

/// <summary>
/// Emits a <c>PopulateGrid(PropertyGrid)</c> method for every <c>[GridEditable]</c> partial class: one row
/// per public settable property, with the editor inferred from the property type and the category /
/// description / range read from the <c>Grid*</c> attributes — resolved at compile time from the Roslyn
/// symbol model, so the running app carries no reflection.
/// </summary>
[Generator]
public sealed class PropertyGridGenerator : IIncrementalGenerator
{
    private const string MarkerAttribute = "Hawkynt.NativeForms.GridEditableAttribute";

    private static readonly DiagnosticDescriptor _MustBePartial = new(
        "NFG001",
        "[GridEditable] type must be a non-nested partial class",
        "'{0}' is marked [GridEditable] but is nested or not partial; the property grid populator cannot be generated",
        "NativeForms",
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var models = context.SyntaxProvider.ForAttributeWithMetadataName(
            MarkerAttribute,
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol);

        context.RegisterSourceOutput(models, static (spc, symbol) => Emit(spc, symbol));
    }

    private static void Emit(SourceProductionContext spc, INamedTypeSymbol type)
    {
        var declaredPartial = false;
        foreach (var reference in type.DeclaringSyntaxReferences)
            if (reference.GetSyntax() is ClassDeclarationSyntax c && c.Modifiers.ToString().Contains("partial"))
                declaredPartial = true;

        if (type.ContainingType is not null || !declaredPartial)
        {
            spc.ReportDiagnostic(Diagnostic.Create(_MustBePartial, type.Locations.Length > 0 ? type.Locations[0] : Location.None, type.Name));
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");

        var hasNamespace = !type.ContainingNamespace.IsGlobalNamespace;
        if (hasNamespace)
        {
            sb.Append("namespace ").Append(type.ContainingNamespace.ToDisplayString()).AppendLine();
            sb.AppendLine("{");
        }

        sb.Append("    partial class ").Append(type.Name).AppendLine();
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>Adds a row per editable property to <paramref name=\"grid\"/> (source-generated).</summary>");
        sb.AppendLine("        public void PopulateGrid(global::Hawkynt.NativeForms.PropertyGrid grid)");
        sb.AppendLine("        {");

        foreach (var member in type.GetMembers())
        {
            if (member is not IPropertySymbol prop
                || prop.IsStatic || prop.IsIndexer
                || prop.DeclaredAccessibility != Accessibility.Public
                || prop.GetMethod is null || prop.SetMethod is null
                || HasAttribute(prop, "GridIgnoreAttribute"))
                continue;

            var display = GetStringArgument(prop, "GridDisplayNameAttribute") ?? prop.Name;
            var category = GetStringArgument(prop, "GridCategoryAttribute");
            var description = GetStringArgument(prop, "GridDescriptionAttribute");
            var reference = "this." + prop.Name;

            sb.Append("            grid.");
            if (prop.Type.TypeKind == TypeKind.Enum)
            {
                sb.Append(HasFlags(prop.Type) ? "AddFlagsEnumRow(" : "AddEnumRow(");
                sb.Append(Quote(display)).Append(", () => ").Append(reference).Append(", v => ").Append(reference).Append(" = v");
                AppendOptions(sb, category, description, null, null);
            }
            else
            {
                var range = GetRange(prop);
                sb.Append("AddRow(");
                sb.Append(Quote(display)).Append(", () => ").Append(reference).Append(", v => ").Append(reference).Append(" = v");
                AppendOptions(sb, category, description, range.HasValue ? range.Value.Min : (double?)null, range.HasValue ? range.Value.Max : (double?)null);
            }

            sb.AppendLine(");");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        if (hasNamespace)
            sb.AppendLine("}");

        spc.AddSource(type.Name + ".PropertyGrid.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void AppendOptions(StringBuilder sb, string? category, string? description, double? minimum, double? maximum)
    {
        if (category is not null)
            sb.Append(", category: ").Append(Quote(category));
        if (description is not null)
            sb.Append(", description: ").Append(Quote(description));
        if (minimum.HasValue)
            sb.Append(", minimum: ").Append(minimum.Value.ToString("R", CultureInfo.InvariantCulture)).Append('D');
        if (maximum.HasValue)
            sb.Append(", maximum: ").Append(maximum.Value.ToString("R", CultureInfo.InvariantCulture)).Append('D');
    }

    private static bool HasAttribute(ISymbol symbol, string attributeName)
    {
        foreach (var attribute in symbol.GetAttributes())
            if (attribute.AttributeClass?.Name == attributeName)
                return true;

        return false;
    }

    private static string? GetStringArgument(ISymbol symbol, string attributeName)
    {
        foreach (var attribute in symbol.GetAttributes())
            if (attribute.AttributeClass?.Name == attributeName
                && attribute.ConstructorArguments.Length > 0
                && attribute.ConstructorArguments[0].Value is string value)
                return value;

        return null;
    }

    private static (double Min, double Max)? GetRange(ISymbol symbol)
    {
        foreach (var attribute in symbol.GetAttributes())
            if (attribute.AttributeClass?.Name == "GridRangeAttribute"
                && attribute.ConstructorArguments.Length >= 2
                && attribute.ConstructorArguments[0].Value is double min
                && attribute.ConstructorArguments[1].Value is double max)
                return (min, max);

        return null;
    }

    private static bool HasFlags(ITypeSymbol type)
    {
        foreach (var attribute in type.GetAttributes())
            if (attribute.AttributeClass?.Name == "FlagsAttribute")
                return true;

        return false;
    }

    private static string Quote(string value)
    {
        var sb = new StringBuilder(value.Length + 2);
        sb.Append('"');
        foreach (var c in value)
            sb.Append(c switch
            {
                '"' => "\\\"",
                '\\' => "\\\\",
                '\n' => "\\n",
                '\r' => "\\r",
                _ => c.ToString(),
            });

        sb.Append('"');
        return sb.ToString();
    }
}
