using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace NativeForms.Generators;

/// <summary>
/// Emits a <c>PopulateGrid(PropertyGrid)</c> method for every <c>[GridEditable]</c> partial class: one row
/// per public settable property, with the editor inferred from the property type and the category /
/// description / range read from the <c>Grid*</c> attributes — resolved at compile time from the Roslyn
/// symbol model, so the running app carries no reflection.
/// </summary>
[Generator]
public sealed class PropertyGridGenerator : IIncrementalGenerator
{
    private const string MarkerAttribute = "Hawkynt.NativeForms.GridEditableAttribute";

    private static readonly DiagnosticDescriptor _MustBePartial = new(
        "NFG001",
        "[GridEditable] type must be a non-nested partial class",
        "'{0}' is marked [GridEditable] but is nested or not partial; the property grid populator cannot be generated",
        "NativeForms",
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    /// <summary>The point of resolving member references at compile time: the reference library resolves
    /// these names by reflection, where a typo is a silent no-op or a run-time throw.</summary>
    private static readonly DiagnosticDescriptor _UnresolvedMember = new(
        "NFG002",
        "Grid attribute names a member that does not exist",
        "'{0}' names '{1}', which is not a readable public property of '{2}'",
        "NativeForms",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor _WrongMemberType = new(
        "NFG003",
        "Grid attribute names a member of the wrong type",
        "'{0}' names '{1}', which must be of type '{2}' but is '{3}'",
        "NativeForms",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var models = context.SyntaxProvider.ForAttributeWithMetadataName(
            MarkerAttribute,
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol);

        context.RegisterSourceOutput(models, static (spc, symbol) => Emit(spc, symbol));
    }

    private static void Emit(SourceProductionContext spc, INamedTypeSymbol type)
    {
        var declaredPartial = false;
        foreach (var reference in type.DeclaringSyntaxReferences)
            if (reference.GetSyntax() is ClassDeclarationSyntax c && c.Modifiers.ToString().Contains("partial"))
                declaredPartial = true;

        if (type.ContainingType is not null || !declaredPartial)
        {
            spc.ReportDiagnostic(Diagnostic.Create(_MustBePartial, type.Locations.Length > 0 ? type.Locations[0] : Location.None, type.Name));
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");

        var hasNamespace = !type.ContainingNamespace.IsGlobalNamespace;
        if (hasNamespace)
        {
            sb.Append("namespace ").Append(type.ContainingNamespace.ToDisplayString()).AppendLine();
            sb.AppendLine("{");
        }

        sb.Append("    partial class ").Append(type.Name).AppendLine();
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>Adds a row per editable property to <paramref name=\"grid\"/> (source-generated).</summary>");
        sb.AppendLine("        public void PopulateGrid(global::Hawkynt.NativeForms.PropertyGrid grid)");
        sb.AppendLine("        {");

        foreach (var member in type.GetMembers())
        {
            if (member is not IPropertySymbol prop
                || prop.IsStatic || prop.IsIndexer
                || prop.DeclaredAccessibility != Accessibility.Public
                || prop.GetMethod is null || prop.SetMethod is null
                || HasAttribute(prop, "GridIgnoreAttribute"))
                continue;

            var display = GetStringArgument(prop, "GridDisplayNameAttribute") ?? prop.Name;
            var category = GetStringArgument(prop, "GridCategoryAttribute");
            var description = GetStringArgument(prop, "GridDescriptionAttribute");
            var reference = "this." + prop.Name;

            sb.Append("            grid.");
            if (prop.Type.TypeKind == TypeKind.Enum)
            {
                sb.Append(HasFlags(prop.Type) ? "AddFlagsEnumRow(" : "AddEnumRow(");
                sb.Append(Quote(display)).Append(", () => ").Append(reference).Append(", v => ").Append(reference).Append(" = v");
                AppendOptions(sb, category, description, null, null);
            }
            else
            {
                var range = GetRange(prop);
                sb.Append("AddRow(");
                sb.Append(Quote(display)).Append(", () => ").Append(reference).Append(", v => ").Append(reference).Append(" = v");
                AppendOptions(sb, category, description, range.HasValue ? range.Value.Min : (double?)null, range.HasValue ? range.Value.Max : (double?)null);
            }

            sb.AppendLine(");");
        }

        sb.AppendLine("        }");
        sb.AppendLine();
        EmitColumns(spc, type, sb);
        sb.AppendLine();
        EmitListView(type, sb);
        sb.AppendLine("    }");
        if (hasNamespace)
            sb.AppendLine("}");

        spc.AddSource(type.Name + ".PropertyGrid.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    /// <summary>
    /// Emits <c>PopulateColumns(DataGridView)</c>: one column per editable property, its kind inferred
    /// from the property type (or forced by <c>[GridColumnKind]</c>), plus the class-level per-row rules.
    /// Every <c>…When</c>/<c>…From</c> attribute names another member, and each of those names is resolved
    /// here — against the symbol model, at compile time — so a typo fails the build.
    /// </summary>
    private static void EmitColumns(SourceProductionContext spc, INamedTypeSymbol type, StringBuilder sb)
    {
        var self = type.ToDisplayString();
        sb.AppendLine("        /// <summary>Adds a column per editable property to <paramref name=\"grid\"/> (source-generated).</summary>");
        sb.AppendLine("        public static void PopulateColumns(global::Hawkynt.NativeForms.DataGridView grid)");
        sb.AppendLine("        {");

        foreach (var member in type.GetMembers())
        {
            if (member is not IPropertySymbol prop
                || prop.IsStatic || prop.IsIndexer
                || prop.DeclaredAccessibility != Accessibility.Public
                || prop.GetMethod is null
                || HasAttribute(prop, "GridIgnoreAttribute"))
                continue;

            var header = GetStringArgument(prop, "GridDisplayNameAttribute") ?? prop.Name;
            var row = $"(({self})r!)";

            sb.Append("            grid.Columns.Add(new global::Hawkynt.NativeForms.DataGridViewColumn(")
              .Append(Quote(header))
              .Append(", r => ").Append(row).Append('.').Append(prop.Name).AppendLine(")");
            sb.AppendLine("            {");
            sb.Append("                Kind = global::Hawkynt.NativeForms.DataGridViewColumnKind.")
              .Append(ColumnKindFor(prop)).AppendLine(",");

            if (GetIntArgument(prop, "GridColumnWidthAttribute") is { } width)
                sb.Append("                Width = ").Append(width.ToString(CultureInfo.InvariantCulture)).AppendLine(",");

            if (GetEnumArgument(prop, "GridColumnSortModeAttribute") is { } sortMode)
                sb.Append("                SortMode = global::Hawkynt.NativeForms.DataGridViewColumnSortMode.")
                  .Append(sortMode).AppendLine(",");

            if (prop.SetMethod is not null)
                sb.Append("                ValueSetter = (r, v) => ").Append(row).Append('.').Append(prop.Name)
                  .Append(" = (").Append(prop.Type.ToDisplayString()).AppendLine(")v!,");
            else
                sb.AppendLine("                ReadOnly = true,");

            if (GetStringArgument(prop, "GridColumnReadOnlyWhenAttribute") is { } readOnlyWhen
                && ResolveBool(spc, type, prop, "[GridColumnReadOnlyWhen]", readOnlyWhen))
                sb.Append("                ReadOnlyCellSelector = r => ").Append(row).Append('.').Append(readOnlyWhen).AppendLine(",");

            EmitImages(sb, spc, type, prop, row);

            sb.AppendLine("            });");
        }

        // Class-level per-row rules, wired to the grid's shipped selectors.
        if (GetStringArgument(type, "GridRowHiddenWhenAttribute") is { } hiddenWhen
            && ResolveBool(spc, type, type, "[GridRowHiddenWhen]", hiddenWhen))
            sb.Append("            grid.RowHiddenSelector = r => ((").Append(self).Append(")r!).").Append(hiddenWhen).AppendLine(";");

        if (GetStringArgument(type, "GridRowSelectableWhenAttribute") is { } selectableWhen
            && ResolveBool(spc, type, type, "[GridRowSelectableWhen]", selectableWhen))
            sb.Append("            grid.RowSelectableSelector = r => ((").Append(self).Append(")r!).").Append(selectableWhen).AppendLine(";");

        if (GetStringArgument(type, "GridRowHeightFromAttribute") is { } heightFrom
            && Resolve(spc, type, type, "[GridRowHeightFrom]", heightFrom, SpecialType.System_Int32, "int"))
            sb.Append("            grid.RowHeightSelector = r => ((").Append(self).Append(")r!).").Append(heightFrom).AppendLine(";");

        sb.AppendLine("        }");
    }

    /// <summary>
    /// Emits the <see cref="Hawkynt.NativeForms.ListView"/> pair: <c>PopulateColumns(ListView)</c> for the
    /// Details-view headers, and <c>ToListViewItem()</c> which turns one model into a row whose sub-item
    /// order matches those headers. Together they make
    /// <c>list.SetDataSource(models, m =&gt; m.ToListViewItem())</c> a one-liner.
    /// </summary>
    private static void EmitListView(INamedTypeSymbol type, StringBuilder sb)
    {
        var properties = new List<IPropertySymbol>();
        foreach (var member in type.GetMembers())
            if (member is IPropertySymbol prop
                && !prop.IsStatic && !prop.IsIndexer
                && prop.DeclaredAccessibility == Accessibility.Public
                && prop.GetMethod is not null
                && !HasAttribute(prop, "GridIgnoreAttribute"))
                properties.Add(prop);

        sb.AppendLine("        /// <summary>Adds a Details-view column per editable property to <paramref name=\"list\"/> (source-generated).</summary>");
        sb.AppendLine("        public static void PopulateColumns(global::Hawkynt.NativeForms.ListView list)");
        sb.AppendLine("        {");
        foreach (var prop in properties)
        {
            var header = GetStringArgument(prop, "GridDisplayNameAttribute") ?? prop.Name;
            sb.Append("            list.Columns.Add(new global::Hawkynt.NativeForms.ColumnHeader(").Append(Quote(header));
            if (GetIntArgument(prop, "GridColumnWidthAttribute") is { } width)
                sb.Append(", ").Append(width.ToString(CultureInfo.InvariantCulture));

            sb.AppendLine("));");
        }

        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>This model as a <see cref=\"global::Hawkynt.NativeForms.ListViewItem\"/> whose");
        sb.AppendLine("        /// sub-items line up with <c>PopulateColumns</c>'s headers (source-generated).</summary>");
        sb.AppendLine("        public global::Hawkynt.NativeForms.ListViewItem ToListViewItem()");
        sb.AppendLine("        {");

        if (properties.Count == 0)
        {
            sb.AppendLine("            return new global::Hawkynt.NativeForms.ListViewItem(string.Empty);");
            sb.AppendLine("        }");
            return;
        }

        sb.Append("            var item = new global::Hawkynt.NativeForms.ListViewItem(")
          .Append(TextOf(properties[0])).AppendLine(");");
        for (var i = 1; i < properties.Count; ++i)
            sb.Append("            item.SubItems.Add(").Append(TextOf(properties[i])).AppendLine(");");

        sb.AppendLine("            return item;");
        sb.AppendLine("        }");
    }

    /// <summary>A property rendered as row text: strings pass through, everything else goes via
    /// <c>ToString()</c>, and a nullable renders empty rather than "null".</summary>
    private static string TextOf(IPropertySymbol prop)
    {
        var access = "this." + prop.Name;
        if (prop.Type.SpecialType == SpecialType.System_String)
            return $"{access} ?? string.Empty";

        // `?.` is only legal where a null can actually occur; a non-nullable value type must call
        // ToString() directly or the generated file will not compile.
        var nullable = prop.Type.IsReferenceType
            || prop.Type is INamedTypeSymbol { ConstructedFrom.SpecialType: SpecialType.System_Nullable_T };

        return nullable ? $"{access}?.ToString() ?? string.Empty" : $"{access}.ToString()";
    }

    /// <summary>The column kind for a property type, unless <c>[GridColumnKind]</c> forces one.</summary>
    /// <summary>
    /// Wires a column's image members from the attributes on the property: one icon beside the text, a
    /// strip of them, or a stack of overlay badges, plus the box they are drawn into and which side of the
    /// text the icon sits on. Each named member is resolved at compile time, so a typo is a build error
    /// rather than a column that silently shows nothing.
    /// </summary>
    private static void EmitImages(
        StringBuilder sb,
        SourceProductionContext spc,
        INamedTypeSymbol type,
        IPropertySymbol prop,
        string row)
    {
        if (GetStringArgument(prop, "GridColumnImageAttribute") is { } image
            && ResolveImage(spc, type, prop, "[GridColumnImage]", image, list: false))
            sb.Append("                ImageSelector = r => ").Append(row).Append('.').Append(image).AppendLine(",");

        if (GetStringArgument(prop, "GridColumnImagesAttribute") is { } images
            && ResolveImage(spc, type, prop, "[GridColumnImages]", images, list: true))
            sb.Append("                ImagesSelector = r => ").Append(row).Append('.').Append(images).AppendLine(",");

        if (GetStringArgument(prop, "GridColumnOverlayImagesAttribute") is { } overlays
            && ResolveImage(spc, type, prop, "[GridColumnOverlayImages]", overlays, list: true))
            sb.Append("                OverlayImagesSelector = r => ").Append(row).Append('.').Append(overlays).AppendLine(",");

        if (GetEnumArgument(prop, "GridColumnTextImageRelationAttribute") is { } relation)
            sb.Append("                TextImageRelation = global::Hawkynt.NativeForms.Drawing.TextImageRelation.")
              .Append(relation).AppendLine(",");

        if (GetAttribute(prop, "GridColumnImageSizeAttribute") is not { } size || size.ConstructorArguments.Length < 2)
            return;

        var width = size.ConstructorArguments[0].Value as int? ?? 0;
        var height = size.ConstructorArguments[1].Value as int? ?? 0;
        sb.Append("                ImageSize = new global::System.Drawing.Size(")
          .Append(width.ToString(CultureInfo.InvariantCulture)).Append(", ")
          .Append(height.ToString(CultureInfo.InvariantCulture)).AppendLine("),");

        if (size.ConstructorArguments.Length > 2 && size.ConstructorArguments[2].Value is bool keep)
            sb.Append("                KeepImageAspectRatio = ").Append(keep ? "true" : "false").AppendLine(",");
    }

    /// <summary>
    /// Resolves a named member to a readable public property producing an image, or a list of them,
    /// reporting the same diagnostics a mistyped condition gets.
    /// </summary>
    private static bool ResolveImage(
        SourceProductionContext spc,
        INamedTypeSymbol type,
        ISymbol site,
        string attribute,
        string name,
        bool list)
    {
        var location = site.Locations.Length > 0 ? site.Locations[0] : Location.None;
        var expected = list
            ? "System.Collections.Generic.IReadOnlyList<Hawkynt.NativeForms.Drawing.IImage>"
            : "Hawkynt.NativeForms.Drawing.IImage";

        foreach (var member in type.GetMembers(name))
        {
            if (member is not IPropertySymbol candidate
                || candidate.GetMethod is null
                || candidate.DeclaredAccessibility != Accessibility.Public)
                continue;

            if (IsImageShaped(candidate.Type, list))
                return true;

            spc.ReportDiagnostic(Diagnostic.Create(
                _WrongMemberType, location, attribute, name, expected, candidate.Type.ToDisplayString()));
            return false;
        }

        spc.ReportDiagnostic(Diagnostic.Create(_UnresolvedMember, location, attribute, name, type.Name));
        return false;
    }

    /// <summary>Whether a type is our image, or a list of them — matched by name, since the generator
    /// cannot reference the runtime assembly it is generating against.</summary>
    private static bool IsImageShaped(ITypeSymbol type, bool list)
    {
        const string ImageName = "Hawkynt.NativeForms.Drawing.IImage";
        if (!list)
            return type.ToDisplayString().TrimEnd('?') == ImageName
                || type.AllInterfaces.Any(i => i.ToDisplayString() == ImageName);

        if (type is not INamedTypeSymbol { IsGenericType: true } named)
            return false;

        return named.TypeArguments.Length == 1
            && named.TypeArguments[0].ToDisplayString().TrimEnd('?') == ImageName;
    }

    private static string ColumnKindFor(IPropertySymbol prop)
    {
        if (GetEnumArgument(prop, "GridColumnKindAttribute") is { } forced)
            return forced;

        var type = prop.Type;
        var underlying = type is INamedTypeSymbol { IsGenericType: true, ConstructedFrom.SpecialType: SpecialType.System_Nullable_T } n
            ? n.TypeArguments[0]
            : type;

        if (underlying.SpecialType == SpecialType.System_Boolean)
            return "Check";

        if (underlying.TypeKind == TypeKind.Enum)
            return HasFlags(underlying) ? "CheckedListBox" : "ComboBox";

        var name = underlying.ToDisplayString();
        return name switch
        {
            "System.DateTime" or "System.DateOnly" => "DateTime",
            "System.TimeOnly" => "TimePicker",
            "System.Drawing.Color" => "Color",
            _ => IsNumeric(underlying) ? "NumericUpDown" : "Text",
        };
    }

    private static bool IsNumeric(ITypeSymbol type) => type.SpecialType
        is SpecialType.System_Byte or SpecialType.System_SByte
        or SpecialType.System_Int16 or SpecialType.System_UInt16
        or SpecialType.System_Int32 or SpecialType.System_UInt32
        or SpecialType.System_Int64 or SpecialType.System_UInt64
        or SpecialType.System_Single or SpecialType.System_Double or SpecialType.System_Decimal;

    /// <summary>Resolves a named member to a readable public <see cref="bool"/> property, reporting a
    /// diagnostic when it is missing or the wrong type.</summary>
    private static bool ResolveBool(SourceProductionContext spc, INamedTypeSymbol type, ISymbol site, string attribute, string name)
        => Resolve(spc, type, site, attribute, name, SpecialType.System_Boolean, "bool");

    private static bool Resolve(
        SourceProductionContext spc,
        INamedTypeSymbol type,
        ISymbol site,
        string attribute,
        string name,
        SpecialType expected,
        string expectedName)
    {
        var location = site.Locations.Length > 0 ? site.Locations[0] : Location.None;
        foreach (var member in type.GetMembers(name))
        {
            if (member is not IPropertySymbol prop || prop.GetMethod is null || prop.DeclaredAccessibility != Accessibility.Public)
                continue;

            if (prop.Type.SpecialType == expected)
                return true;

            spc.ReportDiagnostic(Diagnostic.Create(_WrongMemberType, location, attribute, name, expectedName, prop.Type.ToDisplayString()));
            return false;
        }

        spc.ReportDiagnostic(Diagnostic.Create(_UnresolvedMember, location, attribute, name, type.Name));
        return false;
    }

    /// <summary>The attribute of the given name applied to a symbol, or <see langword="null"/>.</summary>
    private static AttributeData? GetAttribute(ISymbol symbol, string attributeName)
    {
        foreach (var attribute in symbol.GetAttributes())
            if (attribute.AttributeClass?.Name == attributeName)
                return attribute;

        return null;
    }

    private static int? GetIntArgument(ISymbol symbol, string attributeName)
    {
        foreach (var attribute in symbol.GetAttributes())
            if (attribute.AttributeClass?.Name == attributeName
                && attribute.ConstructorArguments.Length > 0
                && attribute.ConstructorArguments[0].Value is int value)
                return value;

        return null;
    }

    /// <summary>The name of an enum-valued attribute argument, for pasting into generated source.</summary>
    private static string? GetEnumArgument(ISymbol symbol, string attributeName)
    {
        foreach (var attribute in symbol.GetAttributes())
        {
            if (attribute.AttributeClass?.Name != attributeName || attribute.ConstructorArguments.Length == 0)
                continue;

            var argument = attribute.ConstructorArguments[0];
            if (argument.Type is not INamedTypeSymbol { TypeKind: TypeKind.Enum } enumType || argument.Value is null)
                continue;

            foreach (var member in enumType.GetMembers())
                if (member is IFieldSymbol { HasConstantValue: true } field && Equals(field.ConstantValue, argument.Value))
                    return field.Name;
        }

        return null;
    }

    private static void AppendOptions(StringBuilder sb, string? category, string? description, double? minimum, double? maximum)
    {
        if (category is not null)
            sb.Append(", category: ").Append(Quote(category));
        if (description is not null)
            sb.Append(", description: ").Append(Quote(description));
        if (minimum.HasValue)
            sb.Append(", minimum: ").Append(minimum.Value.ToString("R", CultureInfo.InvariantCulture)).Append('D');
        if (maximum.HasValue)
            sb.Append(", maximum: ").Append(maximum.Value.ToString("R", CultureInfo.InvariantCulture)).Append('D');
    }

    private static bool HasAttribute(ISymbol symbol, string attributeName)
    {
        foreach (var attribute in symbol.GetAttributes())
            if (attribute.AttributeClass?.Name == attributeName)
                return true;

        return false;
    }

    private static string? GetStringArgument(ISymbol symbol, string attributeName)
    {
        foreach (var attribute in symbol.GetAttributes())
            if (attribute.AttributeClass?.Name == attributeName
                && attribute.ConstructorArguments.Length > 0
                && attribute.ConstructorArguments[0].Value is string value)
                return value;

        return null;
    }

    private static (double Min, double Max)? GetRange(ISymbol symbol)
    {
        foreach (var attribute in symbol.GetAttributes())
            if (attribute.AttributeClass?.Name == "GridRangeAttribute"
                && attribute.ConstructorArguments.Length >= 2
                && attribute.ConstructorArguments[0].Value is double min
                && attribute.ConstructorArguments[1].Value is double max)
                return (min, max);

        return null;
    }

    private static bool HasFlags(ITypeSymbol type)
    {
        foreach (var attribute in type.GetAttributes())
            if (attribute.AttributeClass?.Name == "FlagsAttribute")
                return true;

        return false;
    }

    private static string Quote(string value)
    {
        var sb = new StringBuilder(value.Length + 2);
        sb.Append('"');
        foreach (var c in value)
            sb.Append(c switch
            {
                '"' => "\\\"",
                '\\' => "\\\\",
                '\n' => "\\n",
                '\r' => "\\r",
                _ => c.ToString(),
            });

        sb.Append('"');
        return sb.ToString();
    }
}
